# Generated by Django 3.2.2 on 2021-10-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userr',
            new_name='user',
        ),
    ]
