# Generated by Django 3.2.2 on 2021-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userr_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.jpg', upload_to='user_directory_path_profile'),
        ),
    ]
