# Generated by Django 3.2.2 on 2021-10-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.png', upload_to='user_directory_path_profile'),
        ),
    ]
